server:
  port: 3344
  
spring:
  application:
    name: servicecloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:huang-hai/servicecloud-config.git  #GitHub上面的git仓库名字